import type { Metadata } from "next";
import "../globals.css";
import { Navbar } from "@/component/layout/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="relative w-full flex min-h-screen flex-col">
      <Navbar />
      <main className="flex-1 min-h-full ">{children}</main>
      <footer>{/* Anime Finder Footer */}</footer>
    </div>
  );
}
